# Generated by Django 3.0.4 on 2020-03-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('mediasalario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='datanascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
